export const RANDOM_DISCOUNT_RATE = 0.2;
export const RANDOM_DISCOUNT_INTERVAL = 30000;

export const SUGGESTED_DISCOUNT_RATE = 0.05;
export const SUGGESTED_DISCOUNT_INTERVAL = 60000;

export const PRODUCT_IN_CART_DISCOUNT_QUANTITY_THRESHOLD = 10;

export const BULK_DISCOUNT_RATE = 0.25;
export const BULK_DISCOUNT_QUANTITY_THRESHOLD = 30;
